# Config for Welcome bot https://github.com/behaviorbot/welcome
# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome
# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  –î–∑—è–∫—É–π –∑–∞ –∞–¥–∫—Ä—ã—Ü—Ü–µ —Ç–≤–∞—ë–π –ø–µ—Ä—à–∞–≥–∞ issue, —Å—è–±—Ä–∞ üò∫!

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  –î–∑—è–∫—É–π –∑–∞ —Å—Ç–≤–∞—Ä—ç–Ω–Ω–µ —Ç–≤–∞–π–≥–æ –ø–µ—Ä—à–∞–≥–∞ Pull Request –¥–ª—è Doika üëç! –ö–∞–ª—ñ –ª–∞—Å–∫–∞ –∞–∑–Ω–∞–µ–º—Å—è –∑ [–ø—Ä–∞–≤—ñ–ª–∞–º—ñ –∞—Ñ–∞—Ä–º–ª–µ–Ω–Ω—è PR](/diglabby/doika/blob/develop/CONTRIBUTING.md).

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  –£–†–ê! –ú—ã —Ç–æ–ª—å–∫—ñ —à—Ç–æ –ø—Ä—ã–Ω—è–ª—ñ —ñ –∑–∫–ª–µ—ñ–ª—ñ –ø–µ—Ä—à—ã PR –∞–¥ —Ü—è–±–µ! üéâüéâüéâ –ß–∞–∫–∞–µ–º –Ω–æ–≤—ã—Ö –ø–æ–¥–∑—å–≤—ñ–≥–∞—û!
  ![image](https://media.giphy.com/media/5gXYzsVBmjIsw/giphy.gif)
# It is recommended to include as many gifs and emojis as possible!






# Configuration for Request-info bot - https://github.com/behaviorbot/request-info
# *Required* Comment to reply with
requestInfoReplyComment: >
  üëÄ –ú—ã –±—ã–ª—ñ –± —û–¥–∑—è—á–Ω—ã—è, –∫–∞–ª—ñ –≤—ã –º–∞–≥–ª—ñ –± –¥–∞—Ü—å –Ω–∞–º –±–æ–ª—å—à —ñ–Ω—Ñ–∞—Ä–º–∞—Ü—ã—ñ –∞–± –≥—ç—Ç–∞–π —ñ—à'—é!

# *OPTIONAL* default titles to check against for lack of descriptiveness
# MUST BE ALL LOWERCASE
#requestInfoDefaultTitles:
#  - update readme.md
#  - updates


# *OPTIONAL* Label to be added to Issues and Pull Requests with insufficient information given
# requestInfoLabelToAdd: needs-more-info

# *OPTIONAL* Only warn about insufficient information on these events type
# Keys must be lowercase. Valid values are 'issue' and 'pullRequest'
requestInfoOn:
  pullRequest: false
  issue: true
