# Config for Welcome bot https://github.com/behaviorbot/welcome
# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome
# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  ะะทัะบัะน ะทะฐ ะฐะดะบััััะต ัะฒะฐัะน ะฟะตััะฐะน ัั'ั ั ะณัััะผ ััะฟะฐะทััะพััั!

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  ะะทัะบัะน ะทะฐ ััะฒะฐััะฝะฝะต ัะฒะฐะนะณะพ ะฟะตััะฐะณะฐ pull request ััั! ะะฐะปั ะปะฐัะบะฐ ะฐะทะฝะฐะตะผัั ะท [ะฟัะฐะฒัะปะฐะผั ะฐัะฐัะผะปะตะฝะฝั PR](/CONTRIBUTING.md).

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  ะฃะะ! ะั ัะพะปัะบั ััะพ ะฟััะฝัะปั ั ะทะบะปะตัะปั ะฟะตััั PR ะฐะด ััะฑะต! ๐๐๐ ะงะฐะบะฐะตะผ ะฝะพะฒัั ะฟะพะดะทัะฒัะณะฐั!
  ![image](https://media.giphy.com/media/5gXYzsVBmjIsw/giphy.gif)
# It is recommended to include as many gifs and emojis as possible!
