language: php

php:
  - 7.1.3
  - 7.2
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  # disable xdebug if not coverage
  - if [[ $COVERAGE == "" ]]; then phpenv config-rm xdebug.ini; fi
  - cp .env.example .env
  - composer install --no-interaction --prefer-dist
  - php artisan key:generate

script:
  - composer test:ci

after_script:
  - |
    if [[ $COVERAGE == true && $TRAVIS_BRANCH == "master" ]]; then
      vendor/bin/phpunit --coverage-clover coverage.xml
      wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
      php php-coveralls.phar --verbose
    fi
