language: php

php:
  - 7.1.3
  - 7.2
  - 7.3

before_script:
  - cp .env.ci .env
  - mysql -e 'create database doika;'
  - composer install --no-interaction --prefer-dist

cache:
  directories:
    - $HOME/.composer/cache

script:
  - composer test:ci
